apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawnsql-java-client
  namespace: dawnsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dawnsql-java-client
  template:
    metadata:
      labels:
        app: dawnsql-java-client
    spec:
      containers:
        - name: dawnsql-java-client
          image: dawnsql/dawnsql-java-client:{version}
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dawnsql-java-client
  namespace: dawnsql
spec:
  selector:
    app: dawnsql-java-client
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dawnsql-java-client
  namespace: dawnsql
spec:
  rules:
    - host: client.dawnsql.com
      http:
        paths:
          - backend:
              service:
                name: dawnsql-java-client
                port:
                  number: 8080
            path: /
            pathType: Prefix
