# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI&CD

on: [push]
env:
  VERSION: "1.0.${{ github.run_number }}"
jobs:
  CI:
    name: CI Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: echo version
        run: echo version $VERSION
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: |
            dawnsql/dawnsql-java-client:latest
            dawnsql/dawnsql-java-client:${{ env.VERSION }}

  CD:
    name: CD Job
    needs: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: echo version
        run: echo version $VERSION
      - uses: actions/checkout@v3

      - name: replace version
        run: find . -type f -exec sed -i -e "s/{version}/${{ env.VERSION }}/" {} \;

      - name: Kuberentes (k8s) cli - kubectl
        uses: actions-hub/kubectl@v1.24.0
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f   k8s.yml -n dawnsql